[package]
name = "echo_server"
version = "0.1.0"
authors = ["Paul `Dettorer` Hervot <dettorer@dettorer.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fork = "0.1"
